config/routes.rb
require 'sidekiq/web'

Appointime::Application.routes.draw do
  root :to => 'welcome#show'

  resources :users
    get 'signup', to: 'users#new', as: 'signup'

  resource :session
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about_meghan', to: 'extras#about', as: 'about'
  get 'services', to: 'extras#services', as: 'services'
  get 'faq', to: 'extras#faq', as: 'faq'
  get 'location', to: 'extras#location', as: 'location'

  namespace :admin do
    resource :dashboard, :only => :show
  end

  resources :appointments
    get 'clients', to: 'appointments#clients', as: 'clients'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  include PgSearch
  pg_search_scope :search_by_full_name_or_email, :against => [:first_name, :last_name, :email]

  attr_accessible :first_name,
                  :last_name,
                  :email,
                  :password,
                  :password_confirmation,
                  :phone

  validates_uniqueness_of :email, message: ": This email is already registered."

  validates_presence_of :first_name,
                        :last_name,
                        :email,
                        :phone,
                        :password_digest

  validate :valid_phone_number

  has_many :appointments

  def valid_phone_number
    clean_number = self.phone.gsub(/\D/, "")

    if clean_number.length == 10
      self.phone = clean_number
    elsif clean_number.length == 11 && clean_number[0] == "1"
      self.phone = clean_number[1..10]
    else
      errors.add(:phone, "number is incorrect.  Please input phone in this format: (202) 222-2222")
    end
  end

  def full_name
    [self.first_name, self.last_name].join(" ")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_access, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome, #{@user.first_name}!"
    else
      flash[:error] = "Signup failed"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @appointments = @user.appointments.sort_by{|a| a.appointment_time}
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to user_path(@user), notice: "Profile updated."
    else
      redirect_to edit_user_path(@user), notice: "Update failed"
    end
  end

  def destroy

  end

  def authorize_access
    @user = User.find(params[:id])
    if current_user == nil || (@user != current_user unless current_user.admin)
      flash[:error] = "You are not authorized to view this page."
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def formatted_phone(number)
    n = number.split("")
    area_code = n[0..2].join
    first = n[3..5].join
    last = n[6..10].join
    "(#{area_code}) #{first}-#{last}"
  end
end

app/views/users/_form.html.erb
<div class="span5">
  <fieldset>
    <% if request.fullpath == signup_path %>
      <legend>Sign Up</legend>
    <% else %>
      <legend>Edit Your Info</legend>
    <% end %>

    <%= form_for @user do |f| %>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

      <div class="controls controls-row">
        <%= f.text_field :first_name, :class => "input span2", :placeholder => "First name" %>
        <%= f.text_field :last_name, :class => "input span3", :placeholder => "Last name" %>
      </div>

      <div class="controls controls-row">
        <%= f.text_field :email, :class => "input span3", :placeholder => "Email" %>
        <%= f.text_field :phone, :class => "input span2", :placeholder => "Cell phone" %>
        <p id="cell-waiver">*Please note, I require your cell phone number to send text messages to remind you of appointments a few hours prior.</p>
      </div>

      <% if request.fullpath == signup_path %>
        <div class="controls controls-row">
          <%= f.password_field :password, :class => "input span2", :placeholder => "Password" %>
          <%= f.password_field :password_confirmation, :class => "input span3", :placeholder => "Password confirmation" %>
        </div>
        <%= f.submit "Sign up!", :class => "btn" %>
      <% else %>
        <%= f.submit "Submit", :class => "btn" %>
      <% end %>
    <% end %>
  </fieldset>
</div>

app/views/users/edit.html.erb
<%= render :partial => "form" %>

app/views/users/new.html.erb
<div class="span5">
  <fieldset>
    <legend>Sign Up</legend>

    <%= form_for @user do |f| %>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>

      <div class="controls controls-row">
        <%= f.text_field :first_name, :class => "input span2", :placeholder => "First name" %>
        <%= f.text_field :last_name, :class => "input span3", :placeholder => "Last name" %>
      </div>

      <div class="controls controls-row">
        <%= f.text_field :email, :class => "input span3", :placeholder => "Email" %>
        <%= f.text_field :phone, :class => "input span2", :placeholder => "Cell phone" %>
        <p id="cell-waiver">*Please note, I require your cell phone number to send text messages to remind you of appointments a few hours prior.</p>
      </div>

      <div class="controls controls-row">
      <%= f.password_field :password, :class => "input span2", :placeholder => "Password" %>
      <%= f.password_field :password_confirmation, :class => "input span3", :placeholder => "Password confirmation" %>
      </div>

      <%= f.submit "Sign up!", :class => "btn" %>
    <% end %>
  </fieldset>
</div>

app/views/users/show.html.erb
<h3><%= "My New Leaf Profile" %></h3>

<div class="row">
  <div class="span4">
    <table class="table">
      <tr>
        <td>Name</td>
        <td><%= @user.full_name %></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td>Cell phone</td>
        <td><%= formatted_phone(@user.phone) %></td>
      </tr>
    </table>
  </div>
</div>

<%= button_to "Edit my info", edit_user_path(@user), method: :get, :class => "btn" %>

<div class="row">
<div class="span7">
<h3>Massage History</h3>
<table class="table table-striped">
  <tr>
    <th>Date</th>
    <th>Start Time</th>
    <th>Service</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @appointments.each do |appt| %>
  <tr>
    <td><%= "#{formatted(appt.date)}, #{appt.date.year}" %></td>
    <td><%= formatted(appt.start) %></td>
    <td><%= appt.duration %> minute massage</td>
    <td><%= link_to "View", appointment_path(appt) %></td>
    <% if appt.date > Date.today %>
      <td><%= link_to "Edit", edit_appointment_path(appt) %></td>
      <td><%= link_to "Cancel", appointment_path(appt), method: :delete, :confirm => "Are you sure you want to delete this appointment?" %></td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>
</div>