config/routes.rb
require 'sidekiq/web'

Appointime::Application.routes.draw do
  root :to => 'welcome#show'

  resources :users
    get 'signup', to: 'users#new', as: 'signup'

  resource :session
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about_meghan', to: 'extras#about', as: 'about'
  get 'services', to: 'extras#services', as: 'services'
  get 'faq', to: 'extras#faq', as: 'faq'
  get 'location', to: 'extras#location', as: 'location'

  namespace :admin do
    resource :dashboard, :only => :show
  end

  resources :appointments
    get 'clients', to: 'appointments#clients', as: 'clients'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">x</a>
    <%= msg  %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="row" id="header">
  <center>
    <%= link_to(image_tag("newleaf2.png", :width => 200, :height => 200), "/") %>
    <h4>Massage and Wellness</h4>
  </center>
  <p id="login">
    <% if !current_user %>
      <%= link_to "Log in", login_path %> or <%= link_to "Sign up", signup_path %>
    <% else %>
      <%= "Logged in as #{current_user.first_name}" %>
      (<%= link_to "Log out", logout_path %>)
    <% end %>
  </p>
</div>

app/views/shared/_left_sidebar.html.erb
<div id="sidebar">
  <h3>Meghan Peters, LMT</h3><br>

  <p>
    <strong>Contact</strong><br>
    <i class="icon-phone"></i> 586.604.8834<br>
    <i class="icon-envelope"></i> newleafmassageandwellness@gmail.com<br><br>
    <i class="icon-leaf"></i> Cuyahoga Chiropractic<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;14100 Cedar Road, Suite 100<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;University Heights, OH 44121<br>
  </p>

  <p id="hours">
    <strong>Hours</strong><br>
    Monday: 8 am - 1 pm; 7 - 8:30 pm<br>
    Tuesday: Closed<br>
    Wednesday: 7 - 8:30 pm<br>
    Thursday: 8 am - 1 pm; 6:30 - 8:30 pm<br>
    Friday: 8 am - 8 pm<br>
    Saturday: 8 am - 6 pm<br>
    Sunday: Closed<br>
  </p>
</div>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <ul class="nav">
      <li><a href="/">Home</a></li>
      <li><%= link_to "About Meghan", about_path %></li>
      <li><%= link_to "Services", services_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <li><%= link_to "Location", location_path %></li>
      <li><%= link_to "Book Now!", new_appointment_path %></li>
      <% if current_user && current_user.admin %>
        <li><%= link_to "Dashboard", admin_dashboard_path %></li>
      <% elsif current_user %>
        <li><%= link_to "Account", user_path(current_user) %></a></li>
      <% end %>
    </ul>
  </div>
</div>