config/routes.rb
require 'sidekiq/web'

Appointime::Application.routes.draw do
  root :to => 'welcome#show'

  resources :users
    get 'signup', to: 'users#new', as: 'signup'

  resource :session
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'about_meghan', to: 'extras#about', as: 'about'
  get 'services', to: 'extras#services', as: 'services'
  get 'faq', to: 'extras#faq', as: 'faq'
  get 'location', to: 'extras#location', as: 'location'

  namespace :admin do
    resource :dashboard, :only => :show
  end

  resources :appointments
    get 'clients', to: 'appointments#clients', as: 'clients'

  mount Sidekiq::Web, at: '/sidekiq'
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_filter :require_admin

  def show
    @disable_sidebar = true
    @weekly_appointments = Appointment.for_this_week
    @weekly_appointments_next = Appointment.for_next_week
  end
end

app/views/admin/dashboards/show.html.erb
<div class="span12">
  <center><h3>Admin Dashboard</h3></center>

  <div class="row">
    <div class="span6">
      <center><h4>This week's appointments</h4></center>
      <table class="table table-striped table-bordered">
        <tr>
          <th>Date</th>
          <th>Start</th>
          <th>End</th>
          <th>Client</th>
          <th></th>
        </tr>
        <% @weekly_appointments.each do |appt| %>
          <tr>
            <td><%= formatted(appt.start_time) %></td>
            <td><%= formatted(appt.start_time) %></td>
            <td><%= formatted(appt.ending) %></td>
            <td><%= appt.user.full_name %></td>
            <td><%= link_to "Manage", appointment_path(appt) %></td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="span6">
      <center><h4>Next week's appointments</h4></center>
      <table class="table table-striped table-bordered">
        <tr>
          <th>Date</th>
          <th>Start</th>
          <th>End</th>
          <th>Client</th>
          <th></th>
        </tr>
        <% @weekly_appointments_next.each do |appt| %>
          <tr>
            <td><%= formatted(appt.date) %></td>
            <td><%= formatted(appt.start) %></td>
            <td><%= formatted(appt.end) %></td>
            <td><%= appt.user.full_name %></td>
            <td><%= link_to "Manage", admin_appointment_path(appt) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="span12 new-appt">
      <center><%= button_to "Schedule a new appointment", clients_path, method: :get, :class => "btn btn-large btn-success" %></center>
    </div>
  </div>
</div>